In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")
pd.set_option("display.max_columns", None)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

project_path = "/content/drive/MyDrive/UAH_Project"

for root, dirs, files in os.walk(project_path):
    for file in files:
        if file.endswith((".csv", ".parquet", ".pkl", ".feather")):
            print(os.path.join(root, file))

/content/drive/MyDrive/UAH_Project/datasets/optical_flow/processed/metadata.csv

In [5]:
from pathlib import Path

In [6]:
PROJECT_PATH = Path("/content/drive/MyDrive/UAH_Project")

DATASET_PATH = (
    PROJECT_PATH
    / "datasets"
    / "processed"
    / "uah_dataset_window160.npz"
)

data = np.load(DATASET_PATH)

X = data["X"]
y = data["y"]
groups = data["groups"]

print(X.shape)

(30516, 160, 13)

In [7]:
FEATURE_COLUMNS = [
    "acc_x",
    "acc_y",
    "acc_z",
    "roll",
    "pitch",
    "yaw",
    "speed",
    "heading",
    "lane_offset",
    "phi",
    "front_distance",
    "relative_speed",
    "vehicle_state",
]

In [8]:
flat = X.reshape(-1, X.shape[2])

df = pd.DataFrame(
    flat,
    columns=FEATURE_COLUMNS
)

df.head()

,acc_x,acc_y,acc_z,roll,pitch,yaw,speed,heading,lane_offset,phi,front_distance,relative_speed,vehicle_state
0,0.017,-0.011,0.018,-1.523,0.015,0.012,65.2,331.9,0.0,-0.0,-1.00,-1.00,0.0
1,0.046,0.007,0.019,-1.522,0.012,0.012,65.2,331.9,0.0,-0.0,-1.00,-1.00,0.0
2,0.052,-0.016,0.027,-1.520,0.014,0.011,65.2,331.9,0.0,-0.0,-1.00,-1.00,0.0
3,0.015,-0.016,0.026,-1.523,0.014,0.011,65.2,331.9,0.0,-0.0,17.97,0.99,2.0
4,-0.014,-0.017,0.040,-1.525,0.012,0.011,65.2,331.9,0.0,-0.0,17.97,0.99,2.0

In [9]:
stats = df.describe().T

stats

,count,mean,std,min,25%,50%,75%,max
acc_x,4882560.0,-0.013218,0.039459,-0.454,-0.034,-0.012,0.009,0.539
acc_y,4882560.0,-0.009353,0.069168,-0.618,-0.019,-0.001,0.017,0.376
acc_z,4882560.0,-0.003590,0.032798,-0.659,-0.018,-0.002,0.014,0.248
roll,4882560.0,-1.556857,0.036810,-1.896,-1.578,-1.556,-1.534,-1.231
pitch,4882560.0,-0.011642,0.072532,-0.461,-0.026,-0.004,0.016,0.352
yaw,4882560.0,-0.078858,1.593854,-3.141,-1.022,-0.045,0.788,3.141
speed,4882560.0,93.859741,17.216092,0.000,84.800,91.800,103.200,148.800
heading,4882560.0,181.097634,96.844491,-1.000,88.900,166.600,269.300,355.800
lane_offset,4882560.0,-0.105198,1.071181,-9.000,-0.252,-0.010,0.222,2.698
phi,4882560.0,-0.094107,1.003252,-9.000,-0.017,0.016,0.053,0.598
front_distance,4882560.0,15.363306,26.273044,-1.000,-1.000,-1.000,23.550,222.720
relative_speed,4882560.0,0.082114,1.395381,-1.000,-1.000,-1.000,0.900,13.000
vehicle_state,4882560.0,0.993779,1.034831,0.000,0.000,1.000,2.000,7.000

In [10]:
corr = df.corr(numeric_only=True)

corr

,acc_x,acc_y,acc_z,roll,pitch,yaw,speed,heading,lane_offset,phi,front_distance,relative_speed,vehicle_state
acc_x,1.000000,0.230217,0.153900,0.026524,0.225975,0.013168,0.004203,-0.046465,-0.007136,-0.001832,-0.055628,-0.043520,-0.013431
acc_y,0.230217,1.000000,0.124448,0.088599,0.713715,0.031802,-0.026094,-0.100740,-0.025896,-0.009833,-0.165742,-0.130820,-0.073653
acc_z,0.153900,0.124448,1.000000,0.140573,0.073487,-0.000158,-0.041417,-0.012551,0.012328,0.011588,-0.016921,-0.000523,0.016635
roll,0.026524,0.088599,0.140573,1.000000,0.021701,0.001542,0.037355,0.028081,0.103381,0.095622,0.016326,0.029322,0.014039
pitch,0.225975,0.713715,0.073487,0.021701,1.000000,0.084091,-0.105815,-0.102232,-0.074489,-0.043238,-0.159332,-0.125181,-0.067453
yaw,0.013168,0.031802,-0.000158,0.001542,0.084091,1.000000,-0.016053,-0.204861,0.019204,-0.004898,-0.002506,-0.017517,-0.018450
speed,0.004203,-0.026094,-0.041417,0.037355,-0.105815,-0.016053,1.000000,-0.014915,0.298610,0.324999,0.065051,0.005228,0.117378
heading,-0.046465,-0.100740,-0.012551,0.028081,-0.102232,-0.204861,-0.014915,1.000000,0.014024,0.070921,-0.024271,-0.004482,-0.105945
lane_offset,-0.007136,-0.025896,0.012328,0.103381,-0.074489,0.019204,0.298610,0.014024,1.000000,0.928567,0.068192,0.069335,0.065183
phi,-0.001832,-0.009833,0.011588,0.095622,-0.043238,-0.004898,0.324999,0.070921,0.928567,1.000000,0.062224,0.070054,0.080210
front_distance,-0.055628,-0.165742,-0.016921,0.016326,-0.159332,-0.002506,0.065051,-0.024271,0.068192,0.062224,1.000000,0.955785,0.454544
relative_speed,-0.043520,-0.130820,-0.000523,0.029322,-0.125181,-0.017517,0.005228,-0.004482,0.069335,0.070054,0.955785,1.000000,0.546854
vehicle_state,-0.013431,-0.073653,0.016635,0.014039,-0.067453,-0.018450,0.117378,-0.105945,0.065183,0.080210,0.454544,0.546854,1.000000

In [11]:
from pathlib import Path
import numpy as np

PROJECT_PATH = Path("/content/drive/MyDrive/UAH_Project")

data = np.load(
    PROJECT_PATH /
    "datasets" /
    "processed" /
    "uah_dataset_window160.npz"
)

X = data["X"]

print(X.shape)

(30516, 160, 13)

In [12]:
feature_idx = {
    "acc_x":0,
    "acc_y":1,
    "acc_z":2,
    "roll":3,
    "pitch":4,
    "yaw":5,
    "speed":6,
    "heading":7,
    "lane_offset":8,
    "phi":9,
    "front_distance":10,
    "relative_speed":11,
    "vehicle_state":12
}

simulation_vectors = X[:,0,[
    feature_idx["speed"],
    feature_idx["heading"],
    feature_idx["lane_offset"],
    feature_idx["front_distance"],
    feature_idx["relative_speed"],
    feature_idx["vehicle_state"],
    feature_idx["acc_z"]
]]

simulation_vectors.shape

(30516, 7)

In [13]:
np.save(
    PROJECT_PATH /
    "datasets" /
    "processed" /
    "simulation_vectors.npy",
    simulation_vectors
)

print("Saved.")

Saved.

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

simulation_vectors_scaled = scaler.fit_transform(simulation_vectors)

np.save(
    PROJECT_PATH /
    "datasets" /
    "processed" /
    "simulation_vectors_scaled.npy",
    simulation_vectors_scaled,
)

print("Scaled vectors saved.")

Scaled vectors saved.

In [15]:
import joblib

joblib.dump(
    scaler,
    PROJECT_PATH /
    "datasets" /
    "processed" /
    "simulation_scaler.pkl"
)

print("Scaler saved.")

Scaler saved.

In [16]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".pth"):
            print(os.path.join(root, file))

In [17]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file.endswith(".pth"):
            print(os.path.join(root, file))

In [18]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if "lstm" in file.lower():
            print(os.path.join(root, file))

/content/drive/Othercomputers/Dizüstü Bilgisayarım/Downloads/UAH_Project/src/lstm_model.py
/content/drive/Othercomputers/Dizüstü Bilgisayarım/Downloads/UAH_Project/notebooks/45_LSTM_Baseline.ipynb
/content/drive/MyDrive/Colab Notebooks/45_UAH_LSTM_Baseline.ipynb
/content/drive/MyDrive/Colab Notebooks/47_UAH_LSTM_GroupKFold_Experiments.ipynb
/content/drive/MyDrive/Colab Notebooks/52_UAH_Multimodal_LSTM_ResNet50_Fusion.ipynb
/content/drive/MyDrive/Colab Notebooks/55_UAH_LSTM_Stratified.ipynb
/content/drive/MyDrive/Colab Notebooks/57_UAH_Video_LSTM.ipynb
/content/drive/MyDrive/Colab Notebooks/46_UAH_LSTM_Training.ipynb
/content/drive/MyDrive/Colab Notebooks/48_UAH_LSTM_TripSplit.ipynb
/content/drive/MyDrive/Colab Notebooks/61_UAH_LSTM_Optimization.ipynb
/content/drive/MyDrive/Colab Notebooks/65_UAH_OpticalFlow_CNN_LSTM.ipynb
/content/drive/MyDrive/Colab Notebooks/66_UAH_LSTM_Improvement_Experiments.ipynb
/content/drive/MyDrive/Colab Notebooks/73_UAH_LSTM_Feature_Importance.ipynb
/content/drive/MyDrive/UAH_Project/src/video_lstm_model.py
/content/drive/MyDrive/UAH_Project/src/lstm_model.py
/content/drive/MyDrive/UAH_Project/src/__pycache__/video_lstm_model.cpython-312.pyc
/content/drive/MyDrive/UAH_Project/src/__pycache__/lstm_model.cpython-312.pyc
/content/drive/MyDrive/UAH_Project/notebooks/47_UAH_LSTM_GroupKFold_Experiments.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/52_UAH_Multimodal_LSTM_ResNet50_Fusion.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/55_UAH_LSTM_Stratified.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/57_UAH_Video_LSTM.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/46_UAH_LSTM_Training.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/48_UAH_LSTM_TripSplit.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/45_UAH_LSTM_Baseline.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/61_UAH_LSTM_Optimization.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/65_UAH_OpticalFlow_CNN_LSTM.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/66_UAH_LSTM_Improvement_Experiments.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/73_UAH_LSTM_Feature_Importance.ipynb

In [21]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if "lstm" in file.lower():
            print(os.path.join(root, file))

/content/drive/MyDrive/Colab Notebooks/45_UAH_LSTM_Baseline.ipynb
/content/drive/MyDrive/Colab Notebooks/47_UAH_LSTM_GroupKFold_Experiments.ipynb
/content/drive/MyDrive/Colab Notebooks/52_UAH_Multimodal_LSTM_ResNet50_Fusion.ipynb
/content/drive/MyDrive/Colab Notebooks/55_UAH_LSTM_Stratified.ipynb
/content/drive/MyDrive/Colab Notebooks/57_UAH_Video_LSTM.ipynb
/content/drive/MyDrive/Colab Notebooks/46_UAH_LSTM_Training.ipynb
/content/drive/MyDrive/Colab Notebooks/48_UAH_LSTM_TripSplit.ipynb
/content/drive/MyDrive/Colab Notebooks/61_UAH_LSTM_Optimization.ipynb
/content/drive/MyDrive/Colab Notebooks/65_UAH_OpticalFlow_CNN_LSTM.ipynb
/content/drive/MyDrive/Colab Notebooks/66_UAH_LSTM_Improvement_Experiments.ipynb
/content/drive/MyDrive/Colab Notebooks/73_UAH_LSTM_Feature_Importance.ipynb
/content/drive/MyDrive/UAH_Project/src/video_lstm_model.py
/content/drive/MyDrive/UAH_Project/src/lstm_model.py
/content/drive/MyDrive/UAH_Project/src/__pycache__/video_lstm_model.cpython-312.pyc
/content/drive/MyDrive/UAH_Project/src/__pycache__/lstm_model.cpython-312.pyc
/content/drive/MyDrive/UAH_Project/notebooks/47_UAH_LSTM_GroupKFold_Experiments.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/52_UAH_Multimodal_LSTM_ResNet50_Fusion.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/55_UAH_LSTM_Stratified.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/57_UAH_Video_LSTM.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/46_UAH_LSTM_Training.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/48_UAH_LSTM_TripSplit.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/45_UAH_LSTM_Baseline.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/61_UAH_LSTM_Optimization.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/65_UAH_OpticalFlow_CNN_LSTM.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/66_UAH_LSTM_Improvement_Experiments.ipynb
/content/drive/MyDrive/UAH_Project/notebooks/73_UAH_LSTM_Feature_Importance.ipynb
/content/drive/MyDrive/UAH_Project/models/lstm_window160_dropout02_macrof1_07358.pth